import type { Influencer } from "@/types";

// Mock Spanish influencer database
// In production, this would be imported from the LAYAI repository
export const mockInfluencers: Influencer[] = [
  {
    id: "inf_001",
    name: "María González",
    handle: "mariagonzstyle",
    platform: "Instagram",
    profileImage: "/api/placeholder/400/400",
    followers: 850000,
    engagement: 4.2,
    avgViews: 250000,
    demographics: {
      ageRange: "18-34",
      gender: "70% Female, 30% Male",
      location: ["Spain", "Latin America"],
      interests: ["Fashion", "Lifestyle", "Beauty"],
    },
    contentCategories: ["Fashion", "Lifestyle", "Beauty", "Travel"],
    previousBrands: ["Zara", "Mango", "L'Oréal", "Sephora"],
    rateCard: {
      post: 8000,
      story: 2000,
      reel: 12000,
      video: 15000,
      integration: 25000,
    },
    performance: {
      averageEngagementRate: 4.2,
      averageReach: 300000,
      audienceGrowthRate: 15,
      contentQualityScore: 9.2,
    },
  },
  {
    id: "inf_002",
    name: "Carlos Martínez",
    handle: "carlosfit",
    platform: "Instagram",
    profileImage: "/api/placeholder/400/400",
    followers: 520000,
    engagement: 5.8,
    avgViews: 180000,
    demographics: {
      ageRange: "18-35",
      gender: "45% Female, 55% Male",
      location: ["Spain", "Portugal"],
      interests: ["Fitness", "Health", "Wellness"],
    },
    contentCategories: ["Fitness", "Nutrition", "Lifestyle", "Sports"],
    previousBrands: ["Nike", "Adidas", "MyProtein", "Prozis"],
    rateCard: {
      post: 6000,
      story: 1500,
      reel: 9000,
      video: 12000,
      integration: 18000,
    },
    performance: {
      averageEngagementRate: 5.8,
      averageReach: 200000,
      audienceGrowthRate: 12,
      contentQualityScore: 8.9,
    },
  },
  {
    id: "inf_003",
    name: "Laura Sánchez",
    handle: "laurafoodie",
    platform: "TikTok",
    profileImage: "/api/placeholder/400/400",
    followers: 1200000,
    engagement: 8.5,
    avgViews: 500000,
    demographics: {
      ageRange: "16-28",
      gender: "60% Female, 40% Male",
      location: ["Spain", "Mexico", "Argentina"],
      interests: ["Food", "Cooking", "Lifestyle"],
    },
    contentCategories: ["Food", "Recipes", "Restaurants", "Lifestyle"],
    previousBrands: ["Uber Eats", "Deliveroo", "Coca-Cola", "Nestlé"],
    rateCard: {
      post: 10000,
      story: 2500,
      reel: 15000,
      video: 18000,
      integration: 30000,
    },
    performance: {
      averageEngagementRate: 8.5,
      averageReach: 600000,
      audienceGrowthRate: 25,
      contentQualityScore: 9.5,
    },
  },
  {
    id: "inf_004",
    name: "Alejandro Ruiz",
    handle: "alextech",
    platform: "YouTube",
    profileImage: "/api/placeholder/400/400",
    followers: 650000,
    engagement: 6.2,
    avgViews: 320000,
    demographics: {
      ageRange: "20-40",
      gender: "30% Female, 70% Male",
      location: ["Spain", "USA", "UK"],
      interests: ["Technology", "Gaming", "Reviews"],
    },
    contentCategories: ["Tech Reviews", "Gaming", "Tutorials", "Unboxing"],
    previousBrands: ["Samsung", "Apple", "Logitech", "Razer"],
    rateCard: {
      post: 7000,
      story: 1800,
      reel: 10000,
      video: 20000,
      integration: 35000,
    },
    performance: {
      averageEngagementRate: 6.2,
      averageReach: 400000,
      audienceGrowthRate: 10,
      contentQualityScore: 8.7,
    },
  },
  {
    id: "inf_005",
    name: "Sofia Ramírez",
    handle: "sofiabeauty",
    platform: "Instagram",
    profileImage: "/api/placeholder/400/400",
    followers: 380000,
    engagement: 7.1,
    avgViews: 140000,
    demographics: {
      ageRange: "18-30",
      gender: "85% Female, 15% Male",
      location: ["Spain", "Colombia", "Chile"],
      interests: ["Beauty", "Makeup", "Skincare"],
    },
    contentCategories: ["Beauty", "Makeup Tutorials", "Skincare", "Product Reviews"],
    previousBrands: ["MAC", "Maybelline", "The Ordinary", "Glossier"],
    rateCard: {
      post: 4500,
      story: 1200,
      reel: 7000,
      video: 9000,
      integration: 14000,
    },
    performance: {
      averageEngagementRate: 7.1,
      averageReach: 150000,
      audienceGrowthRate: 18,
      contentQualityScore: 9.0,
    },
  },
  {
    id: "inf_006",
    name: "Diego Torres",
    handle: "diegotravel",
    platform: "Instagram",
    profileImage: "/api/placeholder/400/400",
    followers: 290000,
    engagement: 5.5,
    avgViews: 95000,
    demographics: {
      ageRange: "22-38",
      gender: "55% Female, 45% Male",
      location: ["Spain", "Europe", "Global"],
      interests: ["Travel", "Adventure", "Photography"],
    },
    contentCategories: ["Travel", "Photography", "Adventure", "Hotels"],
    previousBrands: ["Booking.com", "Airbnb", "Samsonite", "GoPro"],
    rateCard: {
      post: 3500,
      story: 900,
      reel: 5500,
      video: 7500,
      integration: 12000,
    },
    performance: {
      averageEngagementRate: 5.5,
      averageReach: 110000,
      audienceGrowthRate: 14,
      contentQualityScore: 8.5,
    },
  },
  {
    id: "inf_007",
    name: "Ana López",
    handle: "anamama",
    platform: "Instagram",
    profileImage: "/api/placeholder/400/400",
    followers: 175000,
    engagement: 8.2,
    avgViews: 75000,
    demographics: {
      ageRange: "25-40",
      gender: "90% Female, 10% Male",
      location: ["Spain"],
      interests: ["Parenting", "Family", "Lifestyle"],
    },
    contentCategories: ["Parenting", "Family Life", "Product Reviews", "Education"],
    previousBrands: ["Pampers", "Fisher-Price", "Amazon", "Decathlon"],
    rateCard: {
      post: 2000,
      story: 500,
      reel: 3500,
      video: 4500,
      integration: 8000,
    },
    performance: {
      averageEngagementRate: 8.2,
      averageReach: 85000,
      audienceGrowthRate: 20,
      contentQualityScore: 8.8,
    },
  },
  {
    id: "inf_008",
    name: "Pablo Moreno",
    handle: "pablocomedy",
    platform: "TikTok",
    profileImage: "/api/placeholder/400/400",
    followers: 980000,
    engagement: 9.8,
    avgViews: 650000,
    demographics: {
      ageRange: "16-30",
      gender: "48% Female, 52% Male",
      location: ["Spain", "Latin America"],
      interests: ["Comedy", "Entertainment", "Trends"],
    },
    contentCategories: ["Comedy", "Sketches", "Trends", "Entertainment"],
    previousBrands: ["Spotify", "Netflix", "Burger King", "Pepsi"],
    rateCard: {
      post: 9000,
      story: 2200,
      reel: 13000,
      video: 16000,
      integration: 25000,
    },
    performance: {
      averageEngagementRate: 9.8,
      averageReach: 750000,
      audienceGrowthRate: 30,
      contentQualityScore: 9.3,
    },
  },
];
